### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Kofi-js**
ggs

### CODE REVIEW

**Review by Kofi-js — COMMENTED** [review]
ignore this...forgot to gitignore .env

**Comment by Iknow6aint** [comment]
ok i will do the rest for user

**Comment by Kofi-js** [comment]
Yo merge. let me pull nibba

**Comment by Kofi-js** [comment]
> ok i will do the rest for user

already did it doe

**Review by Iknow6aint — APPROVED** [review]

**Review by Iknow6aint — APPROVED** [review]

**Review by Iknow6aint — APPROVED** [review]

**Review by Iknow6aint — APPROVED** [review]

**Review by Iknow6aint — APPROVED** [review]

**Review by Iknow6aint — APPROVED** [review]

**Pull request closed without merging**
